@startuml

package jeu #LightBlue{
    class CaseMur
    abstract class Entitee
    class EntiteePJ
    abstract class EntiteePNJ

    class PlateauDeJeu{
        int largeur;
        int hauteur;
        int nombreDeMonstre;
        void initialiserMonstre();
        void genererMonstre();
        void genererCaseTresor();
        void genererCaseTP();
        void genererPlateau();
        void gameEvent();
        Case getCase(int x, int y);
        ArrayList<Case> getCases();
        int getXcase(int index);
        int getYcase(int index);
        int choisirCase();
        boolean isMurDessous(int x, int y);
        Iterator<EntiteeMonstre> monstreIterator();
    }

    class Vertex{
        String id;
        boolean visited;
        void addNeighbor(Vertex v);
        void addPath(Vertex v);
        boolean isVisited();
        void removeNeighbor(Vertex v);
        ArrayList<Vertex> getNeighbors();
        ArrayList<Vertex> getPath();
        boolean hasPath(Vertex target);
        String getId();
        void setVisited(boolean b);
    }

    class Labyrinthe{
        int height;
        int width;
        void create();
        void create(int seed);
        Case getcase(int i, int j);
    }

    abstract class Case{
       boolean blocking;
       boolean isBlocking();
       void setBlocking(boolean isBlocking);
       Color getColor();
       boolean isTresor();
       void event();
    }

    class CaseTresor{
    }

    class EntiteeChronometre{
    }

    class EntiteeSoin{
    }

    class CaseMur{
      Color getColor();
      boolean estMurdeCote();
      void setMurdeCode();
    }

    class FireBomb{
    }


    class CaseChemin{
    }

    class CaseTeleporteur{
    }

    class Entitee(){
        Random random;
    }

    class EntiteeMonstre{
        int positionX;
        int positionY;
        void initialiserMonstre(PlateauDeJeu pdj);
        void deplacement();
    }


    CaseTeleporteur --|> Case
    CaseTresor --|> Case
    CaseMur --|> Case
    CaseChemin --|> Case
    EntiteePNJ --|> Entitee
    EntiteeMonstre --|> EntiteePNJ
    EntiteePJ --|> Entitee

    PlateauDeJeu --"*" Case
    PlateauDeJeu --"*" Entitee
    PlateauDeJeu --"*" EntiteeMonstre
    Labyrinthe --"*" Vertex
    Vertex --"*" Vertex
}

package model #LightGreen{
    class PacmanGame{
        int posPacmanX
        int posPacmanY
        int cercleDiametre;
        int iniPosX;
        int iniPoxY;
        void initialisation();
        void collisionJoueurMonstre();
        void collisionBombeMonstre();
        void fire();
        void teleportation();
    }

    class PacmanPainter{
        int width
        int height
    }

    class PacmanGameController{
        Cmd commandeEnCours
        keyPressed(keyEvent e)
        keyReleased(keyEvent e)
    }
}

package engine #DarkOrange{

    enum Cmd{
      LEFT
      RIGHT
      UP
      DOWN
      IDLE
    }

    interface Game{
        void evolve(Cmd userCmd)
        boolean isFinished()
        void teleportation(int x, int y)
    }


    interface GameController{
        Cmd getCommand()
    }

    class PacmanGameController{
        Cmd commandeEnCours
        keyPressed(keyEvent e)
        keyReleased(keyEvent e)
    }

    interface GamePainter{
        void draw(BufferedImage im
    }


    class DrawingPanel{
        BufferedImage nextImage
        BufferedImage currentImage
        int width
        int height
        void drawGame()
        paint(graphics g)
    }

    class GraphicalInterface{
        void paint()
    }

    class GameEngineGraphical{
        void run()
    }

    class Character{
        int posX
        int posY
        int speed
        int direction
        void move()
        void draw()
    }

    class TextManagerGL{
        int textureId;
        void renderText(string text,float x,float y);
        void initializeCharacters(String fontMetadataPath);
        void parseFntFile(String path);
        Map<String, String> parseValues(String line);
        int loadTexture(String path);
        void cleanup();
    }


    TextManagerGL --"*" Character
    PacmanGame -.-|> Game
    PacmanGameController -.-|> GameController
    PacmanPainter -.-|> GamePainter
    PacmanGameController --"1" Cmd

    DrawingPanel --"1" GamePainter
    GraphicalInterface --"1" DrawingPanel

    GameEngineGraphical --"1" GraphicalInterface
    GameEngineGraphical --"1" Game
    GameEngineGraphical --"1" GameController
    GameEngineGraphical --"1" GamePainter
}

PacmanGame --"1" PlateauDeJeu

package start #LightPink{
    class StartMenu{
        long menuWindow;
        boolean startClickable;
        void run();
        void init();
        void loop();
    }

    class StartButton{
        foat x;
        float y;
        float width;
        float height;
        float borderWidth;
        float borderColor[];
        float buttonColor[];
        boolean isIncluded(float mx, float my);
        void drawButton();
        boolean isHovered(float mx, float my);
        void drawButtonWithBorder();
    }

    class Main{
        boolean StartGame;
    }

    StartMenu --"1" StartButton
    StartMenu --"1" TextManagerGL
}



@enduml